  name: CI/CD Pipeline

  on:
    push:
      branches:
        - master

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 20

        - name: Build Docker image
          run: docker build -t sgroup-devops .

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-southeast-2

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Push to ECR
          run: |
            docker tag sgroup-devops:latest 339712966976.dkr.ecr.ap-southeast-2.amazonaws.com/sgroup-devops:latest
            docker push 339712966976.dkr.ecr.ap-southeast-2.amazonaws.com/sgroup-devops:latest
    deploy:
      needs: build
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: SSH to EC2 and deploy
          uses: appleboy/ssh-action@v0.1.6
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ubuntu
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
                sudo aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com
                sudo docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com/sgroup-devops:latest
                sudo docker stop sgroup-devops-container || true
                sudo docker rm sgroup-devops-container || true
                sudo docker run -d --name sgroup-devops-container -p 3000:3000 -e DB_URI='${{ secrets.DB_URI }}' ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com/sgroup-devops:latest
